"""add is_couple to screen_rows

Revision ID: 4a1d9262f945
Revises: 14076618f793
Create Date: 2026-10-01 11:47:59.863648
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a1d9262f945'
down_revision: Union[str, None] = '14076618f793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_couple', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_rows', schema=None) as batch_op:
        batch_op.drop_column('is_couple')

    # ### end Alembic commands ###